// This file is generated by scripts/update-rugby-data-from-excel.mjs.
// Update src/data/superLeagueMatches.xlsx, then run:
// npm run update-rugby-data

export type Game = {
  status: "FT" | "LIVE" | "TBC" | string;
  kickOff: string;
  home: string;
  away: string;
  venue: string;
  homeScore?: number;
  awayScore?: number;
};

export type FixtureDay = {
  date: string;
  sortDate: string;
  games: Game[];
};

export const fixturesData: FixtureDay[] = [
  {
    date: "Thursday 12th February",
    sortDate: "2026-02-12",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "York Knights",
        away: "Hull KR",
        venue: "LNER Community Stadium",
        homeScore: 19,
        awayScore: 18
      }
    ]
  },
  {
    date: "Friday 13th February",
    sortDate: "2026-02-13",
    games: [
      {
        status: "FT",
        kickOff: "18:00",
        home: "Catalans Dragons",
        away: "Huddersfield Giants",
        venue: "Stade Gilbert Brutus",
        homeScore: 26,
        awayScore: 10
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Leigh Leopards",
        away: "Leeds Rhinos",
        venue: "Leigh Sports Village",
        homeScore: 26,
        awayScore: 14
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Warrington Wolves",
        away: "St Helens",
        venue: "Halliwell Jones Stadium",
        homeScore: 24,
        awayScore: 14
      }
    ]
  },
  {
    date: "Saturday 14th February",
    sortDate: "2026-02-14",
    games: [
      {
        status: "FT",
        kickOff: "17:30",
        home: "Hull FC",
        away: "Bradford Bulls",
        venue: "MKM Stadium",
        homeScore: 27,
        awayScore: 20
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Wakefield Trinity",
        away: "Toulouse Olympique",
        venue: "Belle Vue",
        homeScore: 16,
        awayScore: 18
      }
    ]
  },
  {
    date: "Sunday 15th February",
    sortDate: "2026-02-15",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Castleford Tigers",
        away: "Wigan Warriors",
        venue: "The Jungle",
        homeScore: 16,
        awayScore: 26
      }
    ]
  },
  {
    date: "Friday 20th February",
    sortDate: "2026-02-20",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Bradford Bulls",
        away: "Catalans Dragons",
        venue: "Odsal Stadium",
        homeScore: 28,
        awayScore: 10
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Leeds Rhinos",
        away: "York Knights",
        venue: "Headingley Stadium",
        homeScore: 46,
        awayScore: 14
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "St Helens",
        away: "Leigh Leopards",
        venue: "Totally Wicked Stadium",
        homeScore: 20,
        awayScore: 18
      }
    ]
  },
  {
    date: "Saturday 21st February",
    sortDate: "2026-02-21",
    games: [
      {
        status: "FT",
        kickOff: "18:00",
        home: "Toulouse Olympique",
        away: "Castleford Tigers",
        venue: "Stade Ernest Wallon",
        homeScore: 24,
        awayScore: 12
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Wigan Warriors",
        away: "Hull FC",
        venue: "The Brick Community Stadium",
        homeScore: 34,
        awayScore: 6
      }
    ]
  },
  {
    date: "Sunday 22nd February",
    sortDate: "2026-02-22",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Huddersfield Giants",
        away: "Wakefield Trinity",
        venue: "John Smith's Stadium",
        homeScore: 16,
        awayScore: 18
      }
    ]
  },
  {
    date: "Thursday 26th February",
    sortDate: "2026-02-26",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Wigan Warriors",
        away: "Leigh Leopards",
        venue: "The Brick Community Stadium",
        homeScore: 54,
        awayScore: 0
      }
    ]
  },
  {
    date: "Friday 27th February",
    sortDate: "2026-02-27",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Castleford Tigers",
        away: "Huddersfield Giants",
        venue: "The Jungle",
        homeScore: 34,
        awayScore: 8
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Hull FC",
        away: "York Knights",
        venue: "MKM Stadium",
        homeScore: 16,
        awayScore: 17
      }
    ]
  },
  {
    date: "Saturday 28th February",
    sortDate: "2026-02-28",
    games: [
      {
        status: "FT",
        kickOff: "17:30",
        home: "Warrington Wolves",
        away: "Wakefield Trinity",
        venue: "Halliwell Jones Stadium",
        homeScore: 27,
        awayScore: 16
      },
      {
        status: "FT",
        kickOff: "18:00",
        home: "Catalans Dragons",
        away: "St Helens",
        venue: "Stade Gilbert Brutus",
        homeScore: 4,
        awayScore: 36
      }
    ]
  },
  {
    date: "Sunday 1st March",
    sortDate: "2026-03-01",
    games: [
      {
        status: "FT",
        kickOff: "00:00",
        home: "Hull KR",
        away: "Leeds Rhinos",
        venue: "Craven Park",
        homeScore: 6,
        awayScore: 58
      },
      {
        status: "FT",
        kickOff: "15:00",
        home: "Bradford Bulls",
        away: "Toulouse Olympique",
        venue: "Odsal Stadium",
        homeScore: 18,
        awayScore: 6
      }
    ]
  },
  {
    date: "Thursday 5th March",
    sortDate: "2026-03-05",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Wakefield Trinity",
        away: "Hull FC",
        venue: "Belle Vue",
        homeScore: 14,
        awayScore: 10
      }
    ]
  },
  {
    date: "Friday 6th March",
    sortDate: "2026-03-06",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Leigh Leopards",
        away: "Catalans Dragons",
        venue: "Leigh Sports Village",
        homeScore: 16,
        awayScore: 22
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "York Knights",
        away: "Warrington Wolves",
        venue: "LNER Community Stadium",
        homeScore: 30,
        awayScore: 38
      }
    ]
  },
  {
    date: "Saturday 7th March",
    sortDate: "2026-03-07",
    games: [
      {
        status: "FT",
        kickOff: "17:00",
        home: "Toulouse Olympique",
        away: "Wigan Warriors",
        venue: "Stade Ernest Wallon",
        homeScore: 16,
        awayScore: 36
      },
      {
        status: "FT",
        kickOff: "17:30",
        home: "St Helens",
        away: "Bradford Bulls",
        venue: "Totally Wicked Stadium",
        homeScore: 26,
        awayScore: 22
      }
    ]
  },
  {
    date: "Sunday 8th March",
    sortDate: "2026-03-08",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Huddersfield Giants",
        away: "Hull KR",
        venue: "John Smith's Stadium",
        homeScore: 6,
        awayScore: 32
      },
      {
        status: "FT",
        kickOff: "15:00",
        home: "Leeds Rhinos",
        away: "Castleford Tigers",
        venue: "Headingley Stadium",
        homeScore: 22,
        awayScore: 4
      }
    ]
  },
  {
    date: "Thursday 19th March",
    sortDate: "2026-03-19",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Wigan Warriors",
        away: "York Knights",
        venue: "The Brick Community Stadium",
        homeScore: 23,
        awayScore: 22
      }
    ]
  },
  {
    date: "Friday 20th March",
    sortDate: "2026-03-20",
    games: [
      {
        status: "FT",
        kickOff: "18:00",
        home: "Toulouse Olympique",
        away: "St Helens",
        venue: "Stade Ernest Wallon",
        homeScore: 16,
        awayScore: 30
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Bradford Bulls",
        away: "Huddersfield Giants",
        venue: "Odsal Stadium",
        homeScore: 26,
        awayScore: 14
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Wakefield Trinity",
        away: "Leigh Leopards",
        venue: "Belle Vue",
        homeScore: 18,
        awayScore: 14
      }
    ]
  },
  {
    date: "Saturday 21st March",
    sortDate: "2026-03-21",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Warrington Wolves",
        away: "Castleford Tigers",
        venue: "Halliwell Jones Stadium",
        homeScore: 72,
        awayScore: 6
      },
      {
        status: "FT",
        kickOff: "17:30",
        home: "Catalans Dragons",
        away: "Hull KR",
        venue: "Stade Gilbert Brutus",
        homeScore: 26,
        awayScore: 20
      }
    ]
  },
  {
    date: "Sunday 22nd March",
    sortDate: "2026-03-22",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Hull FC",
        away: "Leeds Rhinos",
        venue: "MKM Stadium",
        homeScore: 24,
        awayScore: 16
      }
    ]
  },
  {
    date: "Thursday 26th March",
    sortDate: "2026-03-26",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Castleford Tigers",
        away: "Bradford Bulls",
        venue: "The Jungle",
        homeScore: 40,
        awayScore: 28
      }
    ]
  },
  {
    date: "Friday 27th March",
    sortDate: "2026-03-27",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Hull KR",
        away: "St Helens",
        venue: "Craven Park",
        homeScore: 52,
        awayScore: 10
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "York Knights",
        away: "Wakefield Trinity",
        venue: "LNER Community Stadium",
        homeScore: 14,
        awayScore: 26
      }
    ]
  },
  {
    date: "Saturday 28th March",
    sortDate: "2026-03-28",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Wigan Warriors",
        away: "Huddersfield Giants",
        venue: "The Brick Community Stadium",
        homeScore: 16,
        awayScore: 34
      },
      {
        status: "FT",
        kickOff: "17:30",
        home: "Leigh Leopards",
        away: "Toulouse Olympique",
        venue: "Leigh Sports Village",
        homeScore: 21,
        awayScore: 20
      }
    ]
  },
  {
    date: "Sunday 29th March",
    sortDate: "2026-03-29",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Hull FC",
        away: "Catalans Dragons",
        venue: "MKM Stadium",
        homeScore: 24,
        awayScore: 20
      },
      {
        status: "FT",
        kickOff: "17:30",
        home: "Leeds Rhinos",
        away: "Warrington Wolves",
        venue: "Headingley Stadium",
        homeScore: 26,
        awayScore: 22
      }
    ]
  },
  {
    date: "Friday 3rd April",
    sortDate: "2026-04-03",
    games: [
      {
        status: "FT",
        kickOff: "12:30",
        home: "Hull KR",
        away: "Hull FC",
        venue: "Craven Park",
        homeScore: 24,
        awayScore: 6
      },
      {
        status: "FT",
        kickOff: "15:00",
        home: "St Helens",
        away: "Wigan Warriors",
        venue: "Totally Wicked Stadium",
        homeScore: 34,
        awayScore: 24
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Bradford Bulls",
        away: "Leeds Rhinos",
        venue: "Odsal Stadium",
        homeScore: 12,
        awayScore: 24
      }
    ]
  },
  {
    date: "Saturday 4th April",
    sortDate: "2026-04-04",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Huddersfield Giants",
        away: "York Knights",
        venue: "John Smith's Stadium",
        homeScore: 34,
        awayScore: 14
      },
      {
        status: "FT",
        kickOff: "17:30",
        home: "Warrington Wolves",
        away: "Leigh Leopards",
        venue: "Halliwell Jones Stadium",
        homeScore: 42,
        awayScore: 6
      },
      {
        status: "FT",
        kickOff: "18:00",
        home: "Catalans Dragons",
        away: "Toulouse Olympique",
        venue: "Stade Gilbert Brutus",
        homeScore: 33,
        awayScore: 26
      }
    ]
  },
  {
    date: "Sunday 5th April",
    sortDate: "2026-04-05",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Castleford Tigers",
        away: "Wakefield Trinity",
        venue: "The Jungle",
        homeScore: 0,
        awayScore: 34
      }
    ]
  },
  {
    date: "Thursday 16th April",
    sortDate: "2026-04-16",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Hull FC",
        away: "St Helens",
        venue: "MKM Stadium",
        homeScore: 14,
        awayScore: 24
      }
    ]
  },
  {
    date: "Friday 17th April",
    sortDate: "2026-04-17",
    games: [
      {
        status: "FT",
        kickOff: "18:30",
        home: "Toulouse Olympique",
        away: "Hull KR",
        venue: "Stade Ernest Wallon",
        homeScore: 0,
        awayScore: 46
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Huddersfield Giants",
        away: "Leeds Rhinos",
        venue: "John Smith's Stadium",
        homeScore: 22,
        awayScore: 56
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "York Knights",
        away: "Leigh Leopards",
        venue: "LNER Community Stadium",
        homeScore: 6,
        awayScore: 18
      }
    ]
  },
  {
    date: "Saturday 18th April",
    sortDate: "2026-04-18",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Wakefield Trinity",
        away: "Bradford Bulls",
        venue: "Belle Vue",
        homeScore: 52,
        awayScore: 12
      },
      {
        status: "FT",
        kickOff: "18:00",
        home: "Catalans Dragons",
        away: "Warrington Wolves",
        venue: "Stade Gilbert Brutus",
        homeScore: 38,
        awayScore: 22
      }
    ]
  },
  {
    date: "Sunday 19th April",
    sortDate: "2026-04-19",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Wigan Warriors",
        away: "Castleford Tigers",
        venue: "The Brick Community Stadium",
        homeScore: 14,
        awayScore: 24
      }
    ]
  },
  {
    date: "Thursday 23rd April",
    sortDate: "2026-04-23",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "York Knights",
        away: "Toulouse Olympique",
        venue: "LNER Community Stadium",
        homeScore: 38,
        awayScore: 14
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Leigh Leopards",
        away: "Huddersfield Giants",
        venue: "Leigh Sports Village",
        homeScore: 30,
        awayScore: 16
      }
    ]
  },
  {
    date: "Friday 24th April",
    sortDate: "2026-04-24",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Leeds Rhinos",
        away: "Catalans Dragons",
        venue: "Headingley Stadium",
        homeScore: 46,
        awayScore: 4
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Warrington Wolves",
        away: "Wigan Warriors",
        venue: "Halliwell Jones Stadium",
        homeScore: 23,
        awayScore: 6
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Castleford Tigers",
        away: "Hull FC",
        venue: "The Jungle",
        homeScore: 10,
        awayScore: 50
      }
    ]
  },
  {
    date: "Saturday 25th April",
    sortDate: "2026-04-25",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Bradford Bulls",
        away: "Hull KR",
        venue: "Odsal Stadium",
        homeScore: 12,
        awayScore: 48
      },
      {
        status: "FT",
        kickOff: "17:30",
        home: "St Helens",
        away: "Wakefield Trinity",
        venue: "Totally Wicked Stadium",
        homeScore: 18,
        awayScore: 12
      }
    ]
  },
  {
    date: "Thursday 30th April",
    sortDate: "2026-04-30",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Hull KR",
        away: "Castleford Tigers",
        venue: "Craven Park",
        homeScore: 50,
        awayScore: 6
      }
    ]
  },
  {
    date: "Friday 1st May",
    sortDate: "2026-05-01",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Leeds Rhinos",
        away: "Wakefield Trinity",
        venue: "Headingley Stadium",
        homeScore: 40,
        awayScore: 22
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "St Helens",
        away: "York Knights",
        venue: "Totally Wicked Stadium",
        homeScore: 40,
        awayScore: 16
      }
    ]
  },
  {
    date: "Saturday 2nd May",
    sortDate: "2026-05-02",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Wigan Warriors",
        away: "Bradford Bulls",
        venue: "The Brick Community Stadium",
        homeScore: 38,
        awayScore: 14
      },
      {
        status: "FT",
        kickOff: "18:00",
        home: "Catalans Dragons",
        away: "Leigh Leopards",
        venue: "Stade Gilbert Brutus",
        homeScore: 18,
        awayScore: 33
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Huddersfield Giants",
        away: "Warrington Wolves",
        venue: "John Smith's Stadium",
        homeScore: 4,
        awayScore: 34
      }
    ]
  },
  {
    date: "Sunday 3rd May",
    sortDate: "2026-05-03",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Hull FC",
        away: "Toulouse Olympique",
        venue: "MKM Stadium",
        homeScore: 4,
        awayScore: 12
      }
    ]
  },
  {
    date: "Thursday 14th May",
    sortDate: "2026-05-14",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Huddersfield Giants",
        away: "St Helens",
        venue: "John Smith's Stadium",
        homeScore: 18,
        awayScore: 26
      }
    ]
  },
  {
    date: "Friday 15th May",
    sortDate: "2026-05-15",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Wakefield Trinity",
        away: "Catalans Dragons",
        venue: "Belle Vue",
        homeScore: 58,
        awayScore: 10
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Wigan Warriors",
        away: "Leeds Rhinos",
        venue: "The Brick Community Stadium",
        homeScore: 24,
        awayScore: 4
      }
    ]
  },
  {
    date: "Saturday 16th May",
    sortDate: "2026-05-16",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "York Knights",
        away: "Castleford Tigers",
        venue: "LNER Community Stadium",
        homeScore: 18,
        awayScore: 24
      },
      {
        status: "FT",
        kickOff: "17:30",
        home: "Leigh Leopards",
        away: "Hull KR",
        venue: "Leigh Sports Village",
        homeScore: 16,
        awayScore: 20
      },
      {
        status: "FT",
        kickOff: "18:00",
        home: "Toulouse Olympique",
        away: "Warrington Wolves",
        venue: "Stade Ernest Wallon",
        homeScore: 16,
        awayScore: 24
      }
    ]
  },
  {
    date: "Sunday 17th May",
    sortDate: "2026-05-17",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Bradford Bulls",
        away: "Hull FC",
        venue: "Odsal Stadium",
        homeScore: 16,
        awayScore: 14
      }
    ]
  },
  {
    date: "Thursday 21st May",
    sortDate: "2026-05-21",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Hull KR",
        away: "Wigan Warriors",
        venue: "Craven Park",
        homeScore: 62,
        awayScore: 4
      }
    ]
  },
  {
    date: "Friday 22nd May",
    sortDate: "2026-05-22",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Leigh Leopards",
        away: "Hull FC",
        venue: "Leigh Sports Village",
        homeScore: 42,
        awayScore: 6
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Leeds Rhinos",
        away: "Huddersfield Giants",
        venue: "Headingley Stadium",
        homeScore: 52,
        awayScore: 0
      }
    ]
  },
  {
    date: "Saturday 23rd May",
    sortDate: "2026-05-23",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Castleford Tigers",
        away: "St Helens",
        venue: "The Jungle",
        homeScore: 30,
        awayScore: 10
      },
      {
        status: "FT",
        kickOff: "18:00",
        home: "Toulouse Olympique",
        away: "Wakefield Trinity",
        venue: "Stade Ernest Wallon",
        homeScore: 18,
        awayScore: 22
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "York Knights",
        away: "Catalans Dragons",
        venue: "LNER Community Stadium",
        homeScore: 22,
        awayScore: 36
      }
    ]
  },
  {
    date: "Sunday 24th May",
    sortDate: "2026-05-24",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Warrington Wolves",
        away: "Bradford Bulls",
        venue: "Halliwell Jones Stadium",
        homeScore: 26,
        awayScore: 12
      }
    ]
  },
  {
    date: "Thursday 4th June",
    sortDate: "2026-06-04",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Leeds Rhinos",
        away: "St Helens",
        venue: "Headingley Stadium",
        homeScore: 24,
        awayScore: 16
      }
    ]
  },
  {
    date: "Friday 5th June",
    sortDate: "2026-06-05",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Warrington Wolves",
        away: "Hull FC",
        venue: "Halliwell Jones Stadium",
        homeScore: 12,
        awayScore: 4
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Bradford Bulls",
        away: "York Knights",
        venue: "Odsal Stadium",
        homeScore: 30,
        awayScore: 20
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Castleford Tigers",
        away: "Leigh Leopards",
        venue: "The Jungle",
        homeScore: 14,
        awayScore: 24
      }
    ]
  },
  {
    date: "Saturday 6th June",
    sortDate: "2026-06-06",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Huddersfield Giants",
        away: "Toulouse Olympique",
        venue: "John Smith's Stadium",
        homeScore: 16,
        awayScore: 36
      },
      {
        status: "FT",
        kickOff: "16:30",
        home: "Wakefield Trinity",
        away: "Hull KR",
        venue: "Belle Vue",
        homeScore: 26,
        awayScore: 24
      },
      {
        status: "FT",
        kickOff: "18:30",
        home: "Catalans Dragons",
        away: "Wigan Warriors",
        venue: "Stade Gilbert Brutus",
        homeScore: 16,
        awayScore: 40
      }
    ]
  },
  {
    date: "Thursday 11th June",
    sortDate: "2026-06-11",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "St Helens",
        away: "Warrington Wolves",
        venue: "Totally Wicked Stadium",
        homeScore: 6,
        awayScore: 18
      }
    ]
  },
  {
    date: "Friday 12th June",
    sortDate: "2026-06-12",
    games: [
      {
        status: "FT",
        kickOff: "18:00",
        home: "Toulouse Olympique",
        away: "Leeds Rhinos",
        venue: "Stade Ernest Wallon",
        homeScore: 24,
        awayScore: 48
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Wakefield Trinity",
        away: "Wigan Warriors",
        venue: "Belle Vue",
        homeScore: 10,
        awayScore: 48
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Hull KR",
        away: "York Knights",
        venue: "Craven Park",
        homeScore: 38,
        awayScore: 6
      }
    ]
  },
  {
    date: "Saturday 13th June",
    sortDate: "2026-06-13",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Hull FC",
        away: "Huddersfield Giants",
        venue: "MKM Stadium",
        homeScore: 36,
        awayScore: 12
      },
      {
        status: "FT",
        kickOff: "18:00",
        home: "Catalans Dragons",
        away: "Castleford Tigers",
        venue: "Stade Gilbert Brutus",
        homeScore: 34,
        awayScore: 28
      }
    ]
  },
  {
    date: "Sunday 14th June",
    sortDate: "2026-06-14",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Bradford Bulls",
        away: "Leigh Leopards",
        venue: "Odsal Stadium",
        homeScore: 12,
        awayScore: 38
      }
    ]
  },
  {
    date: "Thursday 18th June",
    sortDate: "2026-06-18",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Warrington Wolves",
        away: "Leeds Rhinos",
        venue: "Halliwell Jones Stadium",
        homeScore: 6,
        awayScore: 34
      }
    ]
  },
  {
    date: "Friday 19th June",
    sortDate: "2026-06-19",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Hull FC",
        away: "Wakefield Trinity",
        venue: "MKM Stadium",
        homeScore: 10,
        awayScore: 36
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Hull KR",
        away: "Leigh Leopards",
        venue: "Craven Park",
        homeScore: 22,
        awayScore: 8
      }
    ]
  },
  {
    date: "Saturday 20th June",
    sortDate: "2026-06-20",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "York Knights",
        away: "Wigan Warriors",
        venue: "LNER Community Stadium",
        homeScore: 20,
        awayScore: 72
      },
      {
        status: "FT",
        kickOff: "18:00",
        home: "Catalans Dragons",
        away: "Bradford Bulls",
        venue: "Stade Gilbert Brutus",
        homeScore: 34,
        awayScore: 24
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Castleford Tigers",
        away: "Toulouse Olympique",
        venue: "The Jungle",
        homeScore: 36,
        awayScore: 18
      }
    ]
  },
  {
    date: "Sunday 21st June",
    sortDate: "2026-06-21",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "St Helens",
        away: "Huddersfield Giants",
        venue: "Totally Wicked Stadium",
        homeScore: 38,
        awayScore: 6
      }
    ]
  },
  {
    date: "Thursday 25th June",
    sortDate: "2026-06-25",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Warrington Wolves",
        away: "Catalans Dragons",
        venue: "Halliwell Jones Stadium",
        homeScore: 18,
        awayScore: 16
      }
    ]
  },
  {
    date: "Friday 26th June",
    sortDate: "2026-06-26",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Leeds Rhinos",
        away: "Hull KR",
        venue: "Headingley Stadium",
        homeScore: 34,
        awayScore: 8
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Castleford Tigers",
        away: "York Knights",
        venue: "The Jungle",
        homeScore: 14,
        awayScore: 20
      }
    ]
  },
  {
    date: "Saturday 27th June",
    sortDate: "2026-06-27",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Hull FC",
        away: "Wigan Warriors",
        venue: "MKM Stadium",
        homeScore: 16,
        awayScore: 20
      },
      {
        status: "FT",
        kickOff: "17:00",
        home: "Toulouse Olympique",
        away: "Leigh Leopards",
        venue: "Stade Ernest Wallon",
        homeScore: 16,
        awayScore: 40
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Bradford Bulls",
        away: "St Helens",
        venue: "Odsal Stadium",
        homeScore: 10,
        awayScore: 40
      }
    ]
  },
  {
    date: "Sunday 28th June",
    sortDate: "2026-06-28",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Wakefield Trinity",
        away: "Huddersfield Giants",
        venue: "Belle Vue",
        homeScore: 29,
        awayScore: 23
      }
    ]
  },
  {
    date: "Saturday 4th July",
    sortDate: "2026-07-04",
    games: [
      {
        status: "FT",
        kickOff: "12:30",
        home: "Huddersfield Giants",
        away: "York Knights",
        venue: "Hill Dickinson Stadium",
        homeScore: 24,
        awayScore: 36
      },
      {
        status: "FT",
        kickOff: "15:00",
        home: "Hull KR",
        away: "Hull FC",
        venue: "Hill Dickinson Stadium",
        homeScore: 26,
        awayScore: 12
      },
      {
        status: "FT",
        kickOff: "17:30",
        home: "Leigh Leopards",
        away: "Warrington Wolves",
        venue: "Hill Dickinson Stadium",
        homeScore: 24,
        awayScore: 6
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Catalans Dragons",
        away: "Toulouse Olympique",
        venue: "Stade Pierre-Fabre",
        homeScore: 18,
        awayScore: 60
      }
    ]
  },
  {
    date: "Sunday 5th July",
    sortDate: "2026-07-05",
    games: [
      {
        status: "FT",
        kickOff: "12:30",
        home: "Wakefield Trinity",
        away: "Castleford Tigers",
        venue: "Hill Dickinson Stadium",
        homeScore: 48,
        awayScore: 6
      },
      {
        status: "FT",
        kickOff: "15:00",
        home: "Leeds Rhinos",
        away: "Bradford Bulls",
        venue: "Hill Dickinson Stadium",
        homeScore: 50,
        awayScore: 16
      },
      {
        status: "FT",
        kickOff: "17:30",
        home: "Wigan Warriors",
        away: "St Helens",
        venue: "Hill Dickinson Stadium",
        homeScore: 16,
        awayScore: 14
      }
    ]
  },
  {
    date: "Thursday 9th July",
    sortDate: "2026-07-09",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "York Knights",
        away: "Hull FC",
        venue: "LNER Community Stadium",
        homeScore: 20,
        awayScore: 16
      }
    ]
  },
  {
    date: "Friday 10th July",
    sortDate: "2026-07-10",
    games: [
      {
        status: "FT",
        kickOff: "20:00",
        home: "Huddersfield Giants",
        away: "Bradford Bulls",
        venue: "John Smith's Stadium",
        homeScore: 14,
        awayScore: 30
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Wigan Warriors",
        away: "Warrington Wolves",
        venue: "The Brick Community Stadium",
        homeScore: 30,
        awayScore: 18
      }
    ]
  },
  {
    date: "Saturday 11th July",
    sortDate: "2026-07-11",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "Leigh Leopards",
        away: "Castleford Tigers",
        venue: "Leigh Sports Village",
        homeScore: 24,
        awayScore: 18
      },
      {
        status: "FT",
        kickOff: "17:30",
        home: "Hull KR",
        away: "Wakefield Trinity",
        venue: "Craven Park",
        homeScore: 6,
        awayScore: 20
      },
      {
        status: "FT",
        kickOff: "20:00",
        home: "Catalans Dragons",
        away: "Leeds Rhinos",
        venue: "Stade Gilbert Brutus",
        homeScore: 6,
        awayScore: 28
      }
    ]
  },
  {
    date: "Sunday 12th July",
    sortDate: "2026-07-12",
    games: [
      {
        status: "FT",
        kickOff: "15:00",
        home: "St Helens",
        away: "Toulouse Olympique",
        venue: "Totally Wicked Stadium",
        homeScore: 0,
        awayScore: 46
      }
    ]
  },
  {
    date: "Thursday 16th July",
    sortDate: "2026-07-16",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Bradford Bulls",
        away: "Wakefield Trinity",
        venue: "Odsal Stadium"
      }
    ]
  },
  {
    date: "Friday 17th July",
    sortDate: "2026-07-17",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Huddersfield Giants",
        away: "Wigan Warriors",
        venue: "John Smith's Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "St Helens",
        away: "Catalans Dragons",
        venue: "Totally Wicked Stadium"
      }
    ]
  },
  {
    date: "Saturday 18th July",
    sortDate: "2026-07-18",
    games: [
      {
        status: "15:00",
        kickOff: "15:00",
        home: "Warrington Wolves",
        away: "Hull KR",
        venue: "Halliwell Jones Stadium"
      },
      {
        status: "17:30",
        kickOff: "17:30",
        home: "Hull FC",
        away: "Leigh Leopards",
        venue: "MKM Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Toulouse Olympique",
        away: "York Knights",
        venue: "Stade Ernest Wallon"
      }
    ]
  },
  {
    date: "Sunday 19th July",
    sortDate: "2026-07-19",
    games: [
      {
        status: "15:00",
        kickOff: "15:00",
        home: "Castleford Tigers",
        away: "Leeds Rhinos",
        venue: "The Jungle"
      }
    ]
  },
  {
    date: "Thursday 23rd July",
    sortDate: "2026-07-23",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Hull FC",
        away: "Hull KR",
        venue: "MKM Stadium"
      }
    ]
  },
  {
    date: "Friday 24th July",
    sortDate: "2026-07-24",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Wakefield Trinity",
        away: "Castleford Tigers",
        venue: "Belle Vue"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Wigan Warriors",
        away: "St Helens",
        venue: "The Brick Community Stadium"
      }
    ]
  },
  {
    date: "Saturday 25th July",
    sortDate: "2026-07-25",
    games: [
      {
        status: "15:00",
        kickOff: "15:00",
        home: "York Knights",
        away: "Huddersfield Giants",
        venue: "LNER Community Stadium"
      },
      {
        status: "17:30",
        kickOff: "17:30",
        home: "Leigh Leopards",
        away: "Warrington Wolves",
        venue: "Leigh Sports Village"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Toulouse Olympique",
        away: "Catalans Dragons",
        venue: "Stade Ernest Wallon"
      }
    ]
  },
  {
    date: "Sunday 26th July",
    sortDate: "2026-07-26",
    games: [
      {
        status: "15:00",
        kickOff: "15:00",
        home: "Leeds Rhinos",
        away: "Bradford Bulls",
        venue: "Headingley Stadium"
      }
    ]
  },
  {
    date: "Thursday 30th July",
    sortDate: "2026-07-30",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Huddersfield Giants",
        away: "Hull FC",
        venue: "John Smith's Stadium"
      }
    ]
  },
  {
    date: "Friday 31st July",
    sortDate: "2026-07-31",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Hull KR",
        away: "Bradford Bulls",
        venue: "Craven Park"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Leeds Rhinos",
        away: "Toulouse Olympique",
        venue: "Headingley Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Leigh Leopards",
        away: "Wigan Warriors",
        venue: "Leigh Sports Village"
      }
    ]
  },
  {
    date: "Saturday 1st August",
    sortDate: "2026-08-01",
    games: [
      {
        status: "15:00",
        kickOff: "15:00",
        home: "Castleford Tigers",
        away: "Warrington Wolves",
        venue: "The Jungle"
      },
      {
        status: "17:30",
        kickOff: "17:30",
        home: "York Knights",
        away: "St Helens",
        venue: "LNER Community Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Catalans Dragons",
        away: "Wakefield Trinity",
        venue: "Stade Gilbert Brutus"
      }
    ]
  },
  {
    date: "Thursday 6th August",
    sortDate: "2026-08-06",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "St Helens",
        away: "Hull FC",
        venue: "Totally Wicked Stadium"
      }
    ]
  },
  {
    date: "Friday 7th August",
    sortDate: "2026-08-07",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Castleford Tigers",
        away: "Hull KR",
        venue: "The Jungle"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Leigh Leopards",
        away: "York Knights",
        venue: "Leigh Sports Village"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Wakefield Trinity",
        away: "Leeds Rhinos",
        venue: "Belle Vue"
      }
    ]
  },
  {
    date: "Saturday 8th August",
    sortDate: "2026-08-08",
    games: [
      {
        status: "14:00",
        kickOff: "14:00",
        home: "Huddersfield Giants",
        away: "Catalans Dragons",
        venue: "John Smith's Stadium"
      },
      {
        status: "15:00",
        kickOff: "15:00",
        home: "Bradford Bulls",
        away: "Warrington Wolves",
        venue: "Odsal Stadium"
      },
      {
        status: "17:30",
        kickOff: "17:30",
        home: "Wigan Warriors",
        away: "Toulouse Olympique",
        venue: "The Brick Community Stadium"
      }
    ]
  },
  {
    date: "Thursday 13th August",
    sortDate: "2026-08-13",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Hull KR",
        away: "Catalans Dragons",
        venue: "Craven Park"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Leeds Rhinos",
        away: "Leigh Leopards",
        venue: "Headingley Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Warrington Wolves",
        away: "York Knights",
        venue: "Halliwell Jones Stadium"
      }
    ]
  },
  {
    date: "Friday 14th August",
    sortDate: "2026-08-14",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Hull FC",
        away: "Castleford Tigers",
        venue: "MKM Stadium"
      }
    ]
  },
  {
    date: "Saturday 15th August",
    sortDate: "2026-08-15",
    games: [
      {
        status: "15:00",
        kickOff: "15:00",
        home: "Bradford Bulls",
        away: "Wigan Warriors",
        venue: "Odsal Stadium"
      },
      {
        status: "17:30",
        kickOff: "17:30",
        home: "Wakefield Trinity",
        away: "St Helens",
        venue: "Belle Vue"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Toulouse Olympique",
        away: "Huddersfield Giants",
        venue: "Stade Ernest Wallon"
      }
    ]
  },
  {
    date: "Tuesday 18th August",
    sortDate: "2026-08-18",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Hull KR",
        away: "Warrington Wolves",
        venue: "Craven Park"
      }
    ]
  },
  {
    date: "Friday 21st August",
    sortDate: "2026-08-21",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Leigh Leopards",
        away: "Bradford Bulls",
        venue: "Leigh Sports Village"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Wigan Warriors",
        away: "Wakefield Trinity",
        venue: "The Brick Community Stadium"
      }
    ]
  },
  {
    date: "Saturday 22nd August",
    sortDate: "2026-08-22",
    games: [
      {
        status: "15:00",
        kickOff: "15:00",
        home: "St Helens",
        away: "Castleford Tigers",
        venue: "Totally Wicked Stadium"
      },
      {
        status: "17:30",
        kickOff: "17:30",
        home: "Hull KR",
        away: "Toulouse Olympique",
        venue: "Craven Park"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Catalans Dragons",
        away: "Hull FC",
        venue: "Stade Gilbert Brutus"
      }
    ]
  },
  {
    date: "Sunday 23rd August",
    sortDate: "2026-08-23",
    games: [
      {
        status: "15:00",
        kickOff: "15:00",
        home: "Warrington Wolves",
        away: "Huddersfield Giants",
        venue: "Halliwell Jones Stadium"
      },
      {
        status: "15:00",
        kickOff: "15:00",
        home: "York Knights",
        away: "Leeds Rhinos",
        venue: "LNER Community Stadium"
      }
    ]
  },
  {
    date: "Thursday 27th August",
    sortDate: "2026-08-27",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Wigan Warriors",
        away: "Hull KR",
        venue: "The Brick Community Stadium"
      }
    ]
  },
  {
    date: "Friday 28th August",
    sortDate: "2026-08-28",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Castleford Tigers",
        away: "Catalans Dragons",
        venue: "The Jungle"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Huddersfield Giants",
        away: "Leigh Leopards",
        venue: "John Smith's Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "St Helens",
        away: "Leeds Rhinos",
        venue: "Totally Wicked Stadium"
      }
    ]
  },
  {
    date: "Saturday 29th August",
    sortDate: "2026-08-29",
    games: [
      {
        status: "15:00",
        kickOff: "15:00",
        home: "Wakefield Trinity",
        away: "York Knights",
        venue: "Belle Vue"
      },
      {
        status: "17:30",
        kickOff: "17:30",
        home: "Hull FC",
        away: "Warrington Wolves",
        venue: "MKM Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Toulouse Olympique",
        away: "Bradford Bulls",
        venue: "Stade Ernest Wallon"
      }
    ]
  },
  {
    date: "Thursday 3rd September",
    sortDate: "2026-09-03",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Bradford Bulls",
        away: "Castleford Tigers",
        venue: "Odsal Stadium"
      }
    ]
  },
  {
    date: "Friday 4th September",
    sortDate: "2026-09-04",
    games: [
      {
        status: "18:00",
        kickOff: "18:00",
        home: "Toulouse Olympique",
        away: "Hull FC",
        venue: "Stade Ernest Wallon"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Hull KR",
        away: "Huddersfield Giants",
        venue: "Craven Park"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Leigh Leopards",
        away: "St Helens",
        venue: "Leigh Sports Village"
      }
    ]
  },
  {
    date: "Saturday 5th September",
    sortDate: "2026-09-05",
    games: [
      {
        status: "15:00",
        kickOff: "15:00",
        home: "Wakefield Trinity",
        away: "Warrington Wolves",
        venue: "Belle Vue"
      },
      {
        status: "17:00",
        kickOff: "17:00",
        home: "Catalans Dragons",
        away: "York Knights",
        venue: "Stade Gilbert Brutus"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Leeds Rhinos",
        away: "Wigan Warriors",
        venue: "Headingley Stadium"
      }
    ]
  },
  {
    date: "Friday 11th September",
    sortDate: "2026-09-11",
    games: [
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Huddersfield Giants",
        away: "Castleford Tigers",
        venue: "John Smith's Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Leeds Rhinos",
        away: "Hull FC",
        venue: "Headingley Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Leigh Leopards",
        away: "Wakefield Trinity",
        venue: "Leigh Sports Village"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "St Helens",
        away: "Hull KR",
        venue: "Totally Wicked Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Warrington Wolves",
        away: "Toulouse Olympique",
        venue: "Halliwell Jones Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "Wigan Warriors",
        away: "Catalans Dragons",
        venue: "The Brick Community Stadium"
      },
      {
        status: "20:00",
        kickOff: "20:00",
        home: "York Knights",
        away: "Bradford Bulls",
        venue: "LNER Community Stadium"
      }
    ]
  },
  {
    date: "Saturday 19th September",
    sortDate: "2026-09-19",
    games: [
      {
        status: "TBC",
        kickOff: "TBC",
        home: "TBC",
        away: "TBC",
        venue: "To be confirmed"
      },
      {
        status: "TBC",
        kickOff: "TBC",
        home: "TBC",
        away: "TBC",
        venue: "To be confirmed"
      }
    ]
  },
  {
    date: "Saturday 26th September",
    sortDate: "2026-09-26",
    games: [
      {
        status: "TBC",
        kickOff: "TBC",
        home: "TBC",
        away: "TBC",
        venue: "To be confirmed"
      },
      {
        status: "TBC",
        kickOff: "TBC",
        home: "TBC",
        away: "TBC",
        venue: "To be confirmed"
      }
    ]
  },
  {
    date: "Saturday 3rd October",
    sortDate: "2026-10-03",
    games: [
      {
        status: "TBC",
        kickOff: "TBC",
        home: "TBC",
        away: "TBC",
        venue: "To be confirmed"
      }
    ]
  }
];
