// This file is generated by scripts/update-rugby-data-from-excel.mjs.
// Update src/data/superLeagueMatches.xlsx, then run:
// npm run update-rugby-data

export type LeagueTableRow = {
  position: number;
  team: string;
  slug: string;
  played: number;
  won: number;
  lost: number;
  drawn: number;
  pointsFor: number;
  pointsAgainst: number;
  points: number;
};

export const leagueTableData: LeagueTableRow[] = [
  {
    position: 1,
    team: "Leeds Rhinos",
    slug: "leeds-rhinos",
    played: 21,
    won: 17,
    lost: 4,
    drawn: 0,
    pointsFor: 744,
    pointsAgainst: 304,
    points: 34
  },
  {
    position: 2,
    team: "Wakefield Trinity",
    slug: "wakefield-trinity",
    played: 21,
    won: 16,
    lost: 5,
    drawn: 0,
    pointsFor: 587,
    pointsAgainst: 352,
    points: 32
  },
  {
    position: 3,
    team: "Wigan Warriors",
    slug: "wigan-warriors",
    played: 21,
    won: 16,
    lost: 5,
    drawn: 0,
    pointsFor: 607,
    pointsAgainst: 383,
    points: 32
  },
  {
    position: 4,
    team: "Warrington Wolves",
    slug: "warrington-wolves",
    played: 20,
    won: 14,
    lost: 6,
    drawn: 0,
    pointsFor: 526,
    pointsAgainst: 346,
    points: 28
  },
  {
    position: 5,
    team: "Hull KR",
    slug: "hull-kingston-rovers",
    played: 20,
    won: 13,
    lost: 7,
    drawn: 0,
    pointsFor: 588,
    pointsAgainst: 339,
    points: 26
  },
  {
    position: 6,
    team: "Leigh Leopards",
    slug: "leigh-leopards",
    played: 21,
    won: 13,
    lost: 8,
    drawn: 0,
    pointsFor: 466,
    pointsAgainst: 398,
    points: 26
  },
  {
    position: 7,
    team: "St Helens",
    slug: "st-helens",
    played: 21,
    won: 12,
    lost: 9,
    drawn: 0,
    pointsFor: 484,
    pointsAgainst: 460,
    points: 24
  },
  {
    position: 8,
    team: "Catalans Dragons",
    slug: "catalans-dragons",
    played: 21,
    won: 9,
    lost: 12,
    drawn: 0,
    pointsFor: 419,
    pointsAgainst: 621,
    points: 18
  },
  {
    position: 9,
    team: "Toulouse Olympique",
    slug: "toulouse",
    played: 21,
    won: 7,
    lost: 14,
    drawn: 0,
    pointsFor: 432,
    pointsAgainst: 544,
    points: 14
  },
  {
    position: 10,
    team: "York Knights",
    slug: "york-knights",
    played: 21,
    won: 7,
    lost: 14,
    drawn: 0,
    pointsFor: 430,
    pointsAgainst: 613,
    points: 14
  },
  {
    position: 11,
    team: "Castleford Tigers",
    slug: "castleford-tigers",
    played: 21,
    won: 7,
    lost: 14,
    drawn: 0,
    pointsFor: 390,
    pointsAgainst: 658,
    points: 14
  },
  {
    position: 12,
    team: "Bradford Bulls",
    slug: "bradford-bulls",
    played: 21,
    won: 6,
    lost: 15,
    drawn: 0,
    pointsFor: 382,
    pointsAgainst: 629,
    points: 12
  },
  {
    position: 13,
    team: "Hull FC",
    slug: "hull-fc",
    played: 21,
    won: 5,
    lost: 16,
    drawn: 0,
    pointsFor: 353,
    pointsAgainst: 463,
    points: 10
  },
  {
    position: 14,
    team: "Huddersfield Giants",
    slug: "huddersfield-giants",
    played: 21,
    won: 4,
    lost: 17,
    drawn: 0,
    pointsFor: 333,
    pointsAgainst: 631,
    points: 8
  }
];
